
#library(pryr)
library(renv)
library(shiny)
library(glue)
library(shinyjs)
library(ggfortify)
library(ggplot2)
library("gplots")
library(tsne)
library(Rtsne)
#library(pheatmap)
library(plotly)
library("heatmaply")
library(htmlwidgets)
library(dendextend)
library(RColorBrewer)
library(viridis)
library(autoplotly)
library("ggpubr")
library(DT)
library(Seurat)
library(dplyr)
#library(reticulate) # For UMAP
library(tidyverse)
library(heatmap3) # static heatmap
library(KEGG.db)
library(fgsea)
library(org.Hs.eg.db) 
library(org.Mm.eg.db) 
library(GO.db)
library(pathview)
library(gage)
library(monocle)
library("Matrix")
library(cowplot)
library(MAST)
#library("leiden")
